### ISSUE TITLE
environment access non-compatible to console R

### ISSUE THREAD

**Issue by phmarek** [csrhodes/swankr#6]
Hi Christopher,

I know that you don't have much time... but perhaps you can help with that one:

Sending that snippet to R in the console works; but via `swankR` I get `Object "l" not found`

```
pretty10 <- function (x) { l <- log10(x); return(bquote(10 ^ .(l))); }
```

Do you have an idea how to fix that?

I would understand if I needed some higher `parent.frame()` to access variables in the global environment or so, but why is the default wrong for the function that `bquote` is in?

Thanks a lot!

**Comment by csrhodes** [comment]
Philipp Marek <notifications@github.com> writes:

> I know that you don't have much time... but perhaps you can help with that one:
>
> Sending that snippet to R in the console works; but via `swankR` I get `Object "l" not found`
>
> ```
> pretty10 <- function (x) { l <- log10(x); return(bquote(10 ^ .(l))); }
> ```
>
> Do you have an idea how to fix that?

My recollection is that I did slightly crazy things with bquote
internally in the swankr implementation to get things to work.  It
doesn't entirely surprise me that backquoting and unquoting doesn't
work, and it is almost certainly swankr's/my fault.

Of course, now I no longer remember what problem I was solving with this
crazy implementation, nor what the semantics of everything are anyway.
The hideousness is in `swank:listener-eval`, and there are several
pieces of intense dubiousness in it.

Oh, I remember a bit.  What's going on is trying to implement
*read-eval*, to support repl presentations.  We of course don't have
*read-eval*, so I fake it with backquote and unquote.

Since the error you're getting relates to the wrong environment, I
wonder what would happen if the environment arguments to the do.call and
the eval in `swank:listener-eval` were swapped -- that the do.call used
the global environment, and then the eval in the line below used the
default one.

Other ideas welcome!

Cheers,

Christophe

**Comment by phmarek** [comment]
Like this?

```diff
@@ -343,12 +343,12 @@ sendReplResultFunction <- sendReplResult
   ## O how ugly
   string <- gsub("#\\.\\(swank:lookup-presented-object-or-lose([^)]*)\\)", ".(`swank:lookup-presented-object-or-lose`(slimeConnection, sldbState,\\1))", string)
   for(expr in parse(text=string)) {
     expr <- expr
     ## O maybe this is even uglier
-    lookedup <- do.call("bquote", list(expr))
-    tmp <- withVisible(eval(lookedup, envir = globalenv()))
+    lookedup <- do.call("bquote", list(expr), envir = globalenv())
+    tmp <- withVisible(eval(lookedup, envir = parent.frame()))
     if(tmp$visible) {
       sendReplResultFunction(slimeConnection, tmp$value)
     }
   }
   list()
```

Same problem.


> Other ideas welcome!

Ha, from me? Good joke ;)


Well... As this error comes up during _compilation_ and not during _runtime_ of that function, perhaps the `bquote` in `listener-eval` incorrectly tries to interpret that already.
Perhaps we'd need some kind of quoting, as `.()` is here equivalent to (common lisps) `,,` and has no idea of backquote levels?

**Comment by phmarek** [comment]
Looks like this does (a kind of) the trick...

At least I can use `bquote`, and normal things evaluate as expected...


```diff
-    lookedup <- do.call("bquote", list(expr))
-    tmp <- withVisible(eval(lookedup, envir = globalenv()))
+    tmp <- withVisible(eval.parent(expr, 33))
```

(The "33" was a guess based on the output of `.traceback(0)`.)

But I don't understand why evaluating `parent.frame(16)` is the first index where I get `globalenv()` back - I'd have expected that `eval.parent` call to go up that many frames already?


Can you advise, also what breaks when not using the `do.call` line?


Thanks a lot!

**Comment by csrhodes** [comment]
Philipp Marek <notifications@github.com> writes:

> Looks like this does (a kind of) the trick...
>
> At least I can use `bquote`, and normal things evaluate as expected...
>
>
> ```diff
> -    lookedup <- do.call("bquote", list(expr))
> -    tmp <- withVisible(eval(lookedup, envir = globalenv()))
> +    tmp <- withVisible(eval.parent(expr, 33))
> ```

I'm slightly surprised that the eval(expr, envir=globalenv()) doesn't
work once the do.call(bquote...) is removed.  (I have forgotten more
than I can remember about R's environments, though, so...)

> Can you advise, also what breaks when not using the `do.call` line?

Presentations (mouse-clicked to insert them into the current input).
This is basically swankr's killer feature, for demos involving adding
ggplot graphs together, so I have to save it somehow! :-)

I have a couple of train journeys coming up... I'll try to have a look.

Cheers,

Christophe

**Comment by csrhodes** [comment]
I've pushed something which might fix the problem -- could you give it a
try?  For me, after restarting with this new definition, your pretty10
function works as I expected it to.  (There are some lurking places
which might have kept hold of the previous definition of
`swank:listener-eval` by value: if in doubt, restart slime.)

Cheers,

Christophe

**Comment by phmarek** [comment]
Looks good so far, with the (small) bit of preliminary testing I did.

Thanks a lot!

**Comment by phmarek** [comment]
I think you fixed that. Thanks!
